site_name: 数据库课程实验文档

nav:
  - 总述:
    - 实验框架: index.md
    - 测试说明: test.md
    - 实验概述: intro.md
  - 实验:
    - lab 1: lab1.md
    - lab 2: lab2.md
    - lab 3: lab3.md
    - lab 4: lab4.md
    - lab 5: lab5.md
  - 常见问题:
    - FAQ: faq.md

theme:
  name: material
