site_name: 数据库课程实验文档

repo_name: thu-db/thdb-doc
repo_url: https://github.com/thu-db/thdb-doc

nav:
  - 总述:
    - 实验框架: index.md
    - 测试说明: test.md
    - 实验概述: intro.md
  - 实验:
    - lab 1: lab1.md
    - lab 2: lab2.md
    - lab 3: lab3.md
    - lab 4: lab4.md
    - lab 5: lab5.md
  - 常见问题:
    - FAQ: faq.md

theme:
  name: material
  language: zh
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.expand
    - navigation.top

extra_css:
  - stylesheets/extra.css
