site_name: HuaDB 数据库内核课程实验文档
copyright: Copyright &copy; 2023-2024 清华大学计算机系数据库实验室。All Rights Reserved.

repo_name: thu-db/huadb-doc
repo_url: https://github.com/thu-db/huadb-doc

nav:
  - 实验概述: index.md
  - 实验配置: 1-prepare.md
  - 实验框架介绍: 2-overview.md
  - 实验提交要求: 3-submit.md
  - "实验 1: 页面组织与缓存管理":
    - 概述: lab1/1-intro.md
    - 基础功能: lab1/2-basic.md
    - 高级功能: lab1/3-advanced.md
  - "实验 2: 事务处理与故障恢复":
    - 概述: lab2/1-intro.md
    - 基础功能: lab2/2-basic.md
    - 高级功能: lab2/3-advanced.md
  - "实验 3: 多版本并发控制":
    - 概述: lab3/1-intro.md
    - 基础功能: lab3/2-basic.md
    - 高级功能: lab3/3-advanced.md
  - "实验 4: 查询处理":
    - 概述: lab4/1-intro.md
    - 基础功能: lab4/2-basic.md
    - 高级功能: lab4/3-advanced.md
  - "实验 5: 查询优化":
    - 概述: lab5/1-intro.md
    - 基础功能: lab5/2-basic.md
    - 高级功能: lab5/3-advanced.md

theme:
  name: material
  language: zh
  logo: assets/images/logo.png
  font: false
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.top
    - content.code.copy

extra_css:
  - stylesheets/extra.css
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.css

extra_javascript:
  - javascripts/analytics.js
  - javascripts/katex.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/contrib/auto-render.min.js

plugins:
  - search
  - include-markdown

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true

extra:
  analytics:
    provider: google
    property: G-5GB0HPD8DB
  social:
    - icon: fontawesome/solid/paper-plane
      link: mailto:424026452@qq.com
