site_name: 数据库课程实验文档

repo_name: thu-db/thdb-doc
repo_url: https://github.com/thu-db/thdb-doc

nav:
  - 实验简介: index.md
  - 实验描述:
    - "lab 1: 存储": lab1.md
    - "lab 2: 日志": lab2.md
    - "lab 3: 并发控制": lab3.md
    - "lab 4: 优化器": lab4.md
    - "lab 5: 执行器": lab5.md
  - 往年文档:
    - 2023年春:
      - 总述:
        - 实验框架: 2023-spring/index.md
        - 测试说明: 2023-spring/test.md
        - 实验概述: 2023-spring/intro.md
      - 实验:
        - lab 1: 2023-spring/lab1.md
        - lab 2: 2023-spring/lab2.md
        - lab 3: 2023-spring/lab3.md
        - lab 4: 2023-spring/lab4.md
        - lab 5: 2023-spring/lab5.md
      - 常见问题:
        - FAQ: 2023-spring/faq.md

theme:
  name: material
  language: zh
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.expand
    - navigation.top

extra_css:
  - stylesheets/extra.css
