name: ci
on:
  push:
    branches:
      - master
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@v3
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: pip install -r requirements.txt
      - run: mkdocs gh-deploy --force
      - run: sed -i s/G-5GB0HPD8DB/G-HEL2FBFEDQ/g mkdocs.yml
      - run: sed -i s/00e4461e56ebc82fcd2bf2cc9974a464/17c357ea8d2f3947abbbee7437c9458a/g docs/javascripts/analytics.js;
      - run: mkdocs gh-deploy --force -b gitee-pages
  sync:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Sync to Gitee
        uses: wearerequired/git-mirror-action@master
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
        with:
          source-repo: git@github.com:thu-db/huadb-doc.git
          destination-repo: git@gitee.com:thu-db/huadb-doc.git

      - name: Build Gitee Pages
        uses: yanglbme/gitee-pages-action@main
        with:
          gitee-username: hnjylwb
          gitee-password: ${{ secrets.GITEE_PASSWORD }}
          gitee-repo: thu-db/huadb-doc
          branch: gh-pages
